### ISSUE TITLE
Python error line 8

### ISSUE THREAD

**Issue by blib85** [gcarq/portage-lostfiles#9]
Hiya,
Love your work, getting this error on my gentoo machines with GUIs but not on my headless machines.
I'm not a python guy, so any help would be appreciated. Please let me know if you need more info.
Running profile 25 at time of writing "default/linux/amd64/23.0/desktop/gnome (stable)" nothing too out of the ordinary, can post emerge --info if required. Not happening on my headless server running profile 41 "default/linux/amd64/23.0/hardened". Python 3.12 and 3.13 installed on both GUI and headless, not messing with python version control, just using the gentoo defaults.

```
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/lostfiles", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/lostfiles.py", line 327, in main
    process_directory(dirpath, sorted(filenames), args.strict, tracked)
  File "/usr/lib/python3.12/site-packages/lostfiles.py", line 350, in process_directory
    atom = resolve_pkg_from_keepfile(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/lostfiles.py", line 391, in resolve_pkg_from_keepfile
    _, category, remainder = filename.split("_", maxsplit=2)
    ^^^^^^^^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by gcarq** [comment]
Hi, thanks! I think this might be the same issue as in #8 and should hopefully be fixed with https://github.com/gcarq/portage-lostfiles/commit/d64913b502263ddaacfea2a5f5ec817d9a72fb4d. I willl leave the issue open until this has been updated on guru, so that you can test it on your end.

**Comment by blib85** [comment]
Hi, just confirming the new update (app-portage/portage-lostfiles-0.5.6-r1) has solved this issue. Clean output now on my GUI Gentoo machines. Thanks again!
